# Generated by Django 4.2.4 on 2023-10-17 14:37
from datetime import timedelta

from django.db import migrations


def set_delivery_or_warranty(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')
    all_orders = Order.objects.all()

    for order in all_orders:
        if order.status == 'Pending':
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == 'Completed':
            order.warranty = '24 months'
            order.save()
        else:
            order.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0015_order'),
    ]

    operations = [
        migrations.RunPython(set_delivery_or_warranty)
    ]
