# Generated by Django 4.2.4 on 2023-10-26 10:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(limit_value=100, message='Name cannot exceed 100 characters.')])),
                ('location', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=2, message='Location must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(limit_value=200, message='Location cannot exceed 200 characters.')])),
                ('description', models.TextField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(limit_value=Decimal('0.00'), message='Rating must be at least 0.00.'), django.core.validators.MaxValueValidator(limit_value=Decimal('5.00'), message='Rating cannot exceed 5.00.')])),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
            },
        ),
    ]
