# Generated by Django 4.2.4 on 2023-10-26 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_foodcriticrestaurantreview_options_menureview'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menureview',
            new_name='main_app_menu_review_menu_id',
            old_name='main_app_me_menu_id_a83899_idx',
        ),
    ]
