# Generated by Django 4.2.4 on 2023-10-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_foodcriticrestaurantreview_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegularRestaurantReview',
        ),
    ]
