# Generated by Django 4.2.4 on 2023-11-01 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_regularrestaurantreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcriticrestaurantreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Rating cannot exceed 5.')]),
        ),
        migrations.AlterField(
            model_name='menureview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Rating cannot exceed 5.')]),
        ),
        migrations.AlterField(
            model_name='regularrestaurantreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5, 'Rating cannot exceed 5.')]),
        ),
    ]
