# Generated by Django 4.2.4 on 2023-11-01 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_foodcriticrestaurantreview_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcriticrestaurantreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Rating cannot exceed 5.')]),
        ),
        migrations.AlterField(
            model_name='menureview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Rating cannot exceed 5.')]),
        ),
        migrations.AlterField(
            model_name='regularrestaurantreview',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=5, message='Rating cannot exceed 5.')]),
        ),
    ]
