# Generated by Django 4.2.4 on 2023-10-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_car_owner_registration_car_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
