# Generated by Django 4.2.4 on 2023-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_userprofile_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
