# Generated by Django 4.2.4 on 2023-11-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_specialreservation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regularreservation',
            options={},
        ),
    ]
