# Generated by Django 4.2.4 on 2023-10-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_book_movie_music'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='music',
            old_name='descriptions',
            new_name='description',
        ),
    ]
