# Generated by Django 4.2.4 on 2023-10-26 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_descriptions_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Author must be at least 5 characters long')]),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(limit_value=6, message='ISBN must be at least 6 characters long')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=8, message='Director must be at least 8 characters long')]),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=9, message='Artist must be at least 9 characters long')]),
        ),
    ]
