# Generated by Django 4.2.4 on 2023-10-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='class_name',
            field=models.CharField(choices=[('Mage', 'Mage'), ('Warrior', 'Warrior'), ('Assassin', 'Assassin'), ('Scout', 'Scout'), ('Fusion', 'Fusion')], max_length=10),
        ),
    ]
